spring.datasource.url=jdbc:mysql://localhost/algatransito?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=wh0T@_1808

spring.jpa.show-sql=true

spring.flyway.enabled=true
